### ISSUE TITLE
[Bug] Página de post dando 404

### ISSUE THREAD

**Issue by brenopanzolini** [tableless/tableless-static#115]
Não sei exatamente o que aconteceu, porém hoje fui mostrar um artigo que havia escrito para um colega meu e notei que a página está dando 404, porém se observar na página de **/authors** o post está aparecendo.

**URL:** https://tableless.com.br/authors/breno-panzolini/

![img](https://i.imgur.com/c1whaI5.png)

O post **Threads no Node.js 10** está aparecendo na listagem normalmente, porém ao acessar a URL direta: https://tableless.com.br/post-threads-nodejs/ dá 404.

![404](https://i.imgur.com/7m8xOFa.png)

**Comment by TailoMateus** [comment]
@diegoeis Sabe algo sobre esse bug?

**Comment by diegoeis** [comment]
Eita, que louco, sei não. Vou dar uma olhada.

**Comment by brenopanzolini** [comment]
@diegoeis tem alguma ideia do que pode estar acontecendo? Tentei dar uma olhada mas fiquei meio perdido, rs

**Comment by diegoeis** [comment]
Eu não descobri o que foi, mas republiquei! :-)
https://tableless.com.br/threads-nodejs/

Se funcionar, fecha a issue?

**Comment by brenopanzolini** [comment]
Boa, brigadão @diegoeis, funcionou! =)
