### ISSUE TITLE
Problema com os submenus

### ISSUE THREAD

**Issue by dziul** [tableless/tableless-static#12]
Boa noite. Hoje ao acessar o site Tableless no meu notbook, observei um erro no menu. Ao tentar ver os subItens do item **Back-End**, me dei com o seguinte erro, onde nao eh possivel acessa-los por causa de existir outros itens abaixo dele [tela de w1024px - usado para o teste abaixo] :

![error submenu tableless](https://cloud.githubusercontent.com/assets/19353873/25262812/3a888bda-2631-11e7-98de-2a52f85aee68.gif)

Observei que faltou adicionar a propriedade `z-index` no seletor `#tb-menu ul li:hover ul` 
ficando `#tb-menu ul li:hover ul{z-index:10;}` (por exemplo) :

![tabless_new](https://cloud.githubusercontent.com/assets/19353873/25263284/e69521c4-2634-11e7-8574-a203b6a5c9df.gif)

**Comment by danvitoriano** [comment]
Oi @darkziul, Qual seu navegador, versão e sistema operacional?

**Comment by dziul** [comment]
Olá @danvitoriano, 
OS : Window
Navegador: Chorme


Mas esse "bug"  está acontecendo em todos os navegadores. Fiz um teste **Cross Browser**.

Tinha adicionado as propriedades citadas em `https://github.com/tableless/tableless-static/blob/master/themes/tableless/static/css/_header.sass`

no seletor:
```css
#tb-menu
   ul
      li:hover
         ul{
         ...
         z-index:10
         }
```

mas, acho que não tenho permissão.

**Comment by danvitoriano** [comment]
Oi @darkziul vc precisa fazer um fork do repositorio `tableless-static` pro seu user, faz essa correção por gentileza, e envia uma Pull Request do fork no seu usuário pro repositório `tableless-static` do user tableless ;)

**Comment by diegoeis** [comment]
pode ser fork ou melhor, clona o projeto e submete uma nova branch.

**Comment by dziul** [comment]
@diegoeis, fiz como sugerido o @danvitoriano.

**Comment by danvitoriano** [comment]
Valeu @darkziul !

**Comment by danvitoriano** [comment]
PR: #14
