### ISSUE TITLE
Problemas com javascript, comentários e busca

### ISSUE THREAD

**Issue by ricardok** [tableless/tableless-static#13]
Olá,

visualizando o tableless no final do texto falando da mudança para site estático os comentários não funcionaram para mim, segue print.

![image](https://cloud.githubusercontent.com/assets/10894/25437246/165ccfe8-2a6c-11e7-9e1c-f2b2bcd769f7.png)

tentei fazer uma busca e não funciona ao clicar no botão e nem com enter.

**Comment by danvitoriano** [comment]
Oi @ricardok pelo que aparece nesse print que você nos enviou, parece que o JavaScript do seu browser está desabilitado, e por isso está bloqueando o plugin do Discuss.
Tentei ir nas configurações do seu navegador e habilitar o JavaScript. Se você estiver acessando de um computador público, como no trabalho, faculdade ou cybercafé, talvez esta opção não possa ser habilitada por regras de segurança. Sugiro então tentar em outro local ;)

**Comment by ricardok** [comment]
@danvitoriano para que vou desabilita javascript ? Mas anyway, só para constar depois de publicar a issue, milagrosamente agora esta funcionando, mesmo assim agradeço.

**Comment by danvitoriano** [comment]
Oi @ricardok eu só disse baseado que estava aparecendo na imagem que você postou. Se você desabilitaria o JavaScript ou não, aí vai de você. Por favor não se ofenda, em nenhum momento tentei ser grosseiro contigo. Estou aqui unicamente para ajudar, não ganho nada com isso.
