### ISSUE TITLE
Sem pagina de anuncio, não tem anuncio

### ISSUE THREAD

**Issue by rafaelvicio** [tableless/tableless-static#16]
A nossa pagina de anuncio esta recebendo erro 404
https://tableless.com.br/anuncie/

**Comment by shadowmaru** [comment]
O link no rodapé está indo para https://tableless.com.br/anuncie-no-tableless/

Onde você achou esse link, @rafaelvicio?

**Comment by rafaelvicio** [comment]
Ela esta aqui, https://tableless.com.br/seja-um-autor/
Desculpe, deveria ter conferido outros links

**Comment by danvitoriano** [comment]
Arrumado na PR #17 
Obrigado @rafaelvicio
