### ISSUE TITLE
erro 404 nas imagens de posts

### ISSUE THREAD

**Issue by angelolucas** [tableless/tableless-static#3]
Vários posts perderam suas imagens.
Exemplos:
https://tableless.com.br/use-as-facilidades-do-css-4-hoje/
https://tableless.com.br/centralizando-conteudo-na-vertical-e-horizontal-com-css-flexbox/
https://tableless.com.br/criando-layouts-com-susy-framework/
https://tableless.com.br/entendendo-os-valores-initial-e-inherit-do-css/

**Comment by danvitoriano** [comment]
Rolou um backup das imagens do Wordpress @diegoeis ? Ou será que essas perderam mesmo?
