### ISSUE TITLE
Artigo quebrado: Email Marketing – O Inferno – Parte 1

### ISSUE THREAD

**Issue by amdrade** [tableless/tableless-static#44]
O post [Email Marketing – O Inferno – Parte 1](https://tableless.com.br/email-marketing-o-inferno-parte-1/) só mostra até a metade, olhando no código, tem uma tag `<style>` no meio do texto, acredito que seja esse o problema.

**Comment by TailoMateus** [comment]
Fernando, é isso mesmo, consegue corrigir?

**Comment by amdrade** [comment]
@TailoMateus submeti a correção #45
