### ISSUE TITLE
Tag title vazia listagem de posts por categoria

### ISSUE THREAD

**Issue by amdrade** [tableless/tableless-static#51]
Nas páginas que listam todos os posts por categoria a tag `title` ficou vazia. A página  [Todos os posts](https://tableless.com.br/todos-os-posts/) apresenta o mesmo problema.

**Comment by TailoMateus** [comment]
@amdrade, consegue corrigir?

**Comment by amdrade** [comment]
Vou tentar.

Em 10/10/2017 10:56, "Tailo Mateus Gonsalves" <notifications@github.com>
escreveu:

**Comment by amdrade** [comment]
@TailoMateus submeti a PR com a correção #58

**Comment by TailoMateus** [comment]
Acho que a página "Todos os posts" ainda ficou sem title, mas nos posts por categoria ficou bom.

**Comment by amdrade** [comment]
Vou verificar

**Comment by TailoMateus** [comment]
Acredito que agora está bom. Vou fechar a issue. Obrigado @amdrade
