### ISSUE TITLE
Texto quebrado do post: Como criar um time de Dados eficiente dentro da sua organização

### ISSUE THREAD

**Issue by amdrade** [tableless/tableless-static#60]
O primeiro parágrafo do post [Como criar um time de Dados eficiente dentro da sua organização](https://tableless.com.br/como-criar-um-time-dados-eficiente-na-organizacao/) começa com `h2` e é quebrado no meio da frase.

**Comment by TailoMateus** [comment]
Obrigado @amdrade, corrigi.
