### ISSUE TITLE
CSS3D mais a fundo

### ISSUE THREAD

**Issue by angelolucas** [tableless/tableless-static#64]
À alguns meses venho estudando CSS3D mais a fundo, e hoje com mais tempo livre, tenho interesse em criar um artigo pra compartilhar um pouco desse conhecimento. Só preciso de uma orientação pra saber como proceder, porque esse seria meu primeiro artigo.

Descobri (não encontrei na web) uma técnica simples de criar uma grid 3D com um efeito cascata. Onde os blocos vão herdando as propriedades CSS dos blocos anteriores. Então, basicamente 6 linhas com rotate de 60deg, forma um hexágono:

1˚ linha com 60˚
2˚ linha com 60˚ + 60˚ (herança do anterior) = 120˚
3˚ linha com 60˚ + 120˚(herança dos anteriores) = 180˚
4˚ linha com 60˚ + 180˚ (herança dos anteriores) = 240˚
5˚ linha com 60˚ + 240˚ (herança dos anteriores) = 300˚
6˚ linha com 60˚ + 300˚ (herança dos anteriores) = 360˚

Esse foi um exemplo em 2D. No 3D fica bem mais interessante:
https://angelolucas.github.io/grid-3d/

E pra herança acontecer é necessário alinhar as tags HTML dos blocos um dentro do outro:
```
<span>
    <span>
        <span>
            <span>
                <span>
                    <span>
                    </span>
                </span>
            </span>
        </span>
    </span>
</span>
```
Concordo que o HTML não fica tão bonito. Mas a semântica aqui, acho que não é necessária.

E aqui um estádio de futebol que fiz (esse é um projeto pra estressar a técnica, então se o rpm não estiver legal, já sabe):
https://codepen.io/angelolucas/pen/evojyW

Esse seria um tutorial avançado. Antes, é necessário que o leitor tenha um entendimento básico de CSS3D. E o @diegoeis  já escreveu sobre isso:

[Introdução ao CSS 3D – Flip Card](https://www.tableless.com.br/introducao-ao-css-3d-flip-card/)
Mas o leitor precisa conhecer outras propriedades do 3D. E o artigo é de 6 anos atrás, a menção ao  suporte não está atualizada.

[CSS Transforms](https://www.tableless.com.br/css-transforms/)
Ensina a usar a propriedade que faz a mágica do 3D. Mas o foco do artigo é 2D.

Talvez seja uma boa idéia ensinar essa base antes. Desenvolvi um projeto didático que pode ser incluído no artigo através do CodePen: https://angelolucas.github.io/CSS3D-manipulation/. Aprender com uma interação prática fica bem melhor.

[Comecei a escrever aqui](https://github.com/angelolucas/tableless-static/blob/master/content/posts/CSS3D-a-fundo.md). Precisei clonar o Tableless porque usei alguns Shortcodes do Hugo que só dá pra ver no server. Ainda está no osso do osso.

Críticas são muito bem vindas.

Um abraço, obrigado.

**Comment by TailoMateus** [comment]
Opa @angelolucas, não entendi muito bem a issue. Mas se você quer escrever um artigo, manda um PR com o formato descrito aqui: https://tableless.com.br/seja-um-autor/ 

Aí vamos dar continuidade na revisão. Qualquer coisa só pedir. Obrigado!

**Comment by angelolucas** [comment]
Ok @TailoMateus 
Obrigado pela atenção
