### ISSUE TITLE
[bug] Página de posts por author não funcionando

### ISSUE THREAD

**Issue by brenopanzolini** [tableless/tableless-static#65]
As páginas de post por autor não estão trazendo nenhum resultado:

Exemplo: [https://tableless.com.br/author/diego-eis/](https://tableless.com.br/author/diego-eis/)

Dei uma olhada na **taxonomy**: [https://github.com/tableless/tableless/blob/master/layouts/taxonomy/author.html](https://github.com/tableless/tableless/blob/master/layouts/taxonomy/author.html), mas aparentemente não teve nenhuma alteração recente. Estou achando que algum script que fazia essa função foi removido.

Alguma ideia do que pode estar acontecendo?

**Comment by ghost** [comment]
O erro está no URL. O certo é este: https://tableless.com.br/authors/diego-eis/
