### ISSUE TITLE
Automatizando sua vida com Crontab

### ISSUE THREAD

**Issue by ghost** [tableless/tableless-static#67]
Olá Diego, quanto tempo né?
Lembra quando disse que iria escrever um artigo? #23 
Eu escrevi recentemente um artigo, espero que você leia e me diga aonde eu errei.
Att.

**Comment by ghost** [comment]
Recentemente eu dei uma revisada no artigo, ele ficou muito ruim. Desisti.

**Comment by TailoMateus** [comment]
Oi @drelldeveloper, caso você queira posso revisa-lo e apontar melhorias. O que acha?
