### ISSUE TITLE
Texto no lado direito da página

### ISSUE THREAD

**Issue by theuves** [tableless/tableless-static#7]
Acho estranho ler um texto que está no lado direito da página.

Creio que seria mais agradável se estivesse no lado esquerdo ou no centro.

(Talvez só eu ache isto.)

**Comment by gregoryfm** [comment]
Concordo, especialmente quando acessa pelo tablet. 
O texto fica todo espremido no lado direito.
Creio que o mais natural seria no meio, em qualquer dispositivo.

**Comment by diegoeis** [comment]
Eu estou fazendo um teste com adsense. Última vez que fiz isso, houveram mais cliques quando a sidebar estava do lado esquerdo. 
Se eu ver que não houve melhoras, também acho que do lado direito é melhor.

Coloquei tablets para serem vistos com o breakpoint mobile.

---

Fechando essa issue.
