### ISSUE TITLE
Texto de artigo duplicado

### ISSUE THREAD

**Issue by rafaelvicio** [tableless/tableless-static#8]
O seguinte artigo esta com o seu conteúdo duplicado: https://tableless.com.br/introducao-ao-ionic-framework/

**Comment by danvitoriano** [comment]
Valeu por avisar @rafaelvicio !
Quando for assim, forka o projeto do tableless-static e manda uma PR pra cá!
:smiley:

**Comment by danvitoriano** [comment]
resolvido @rafaelvicio
